### ISSUE TITLE
Setup REUSE compliance

### ISSUE THREAD

**Issue by murtoM** [mtijas/lopokulu#1]
All the files in the repository should have copyright and licensing information in the source header, or declared in `.reuse/dep5` Debian copyright format.

**Comment by murtoM** [comment]
Also how should the contributors be declared in `FileCopyrightText`? Do we create `CONTRIBUTORS.md` with contributor names or should we write them out it each file?

**Comment by mtijas** [comment]
Reflecting this in Jira LOP-35.

**Comment by mtijas** [comment]
> Also how should the contributors be declared in `FileCopyrightText`? Do we create `CONTRIBUTORS.md` with contributor names or should we write them out it each file?

I guess we could write contributor information to each file separately to make contributor information more visible. Not that I personally need/want that visibility but just to keep copyright information where it will get noticed more likely.
